spring:
  application:
    name: Rag-knowledge-system
  data:
    redis:
      host: localhost
      port: 6379
      password: sty01725
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple:
        prefetch: 1
        acknowledge-mode: auto
  datasource:
    url: jdbc:mysql://localhost:3306/rag_knowledge?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: rag-knowledge

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

jwt:
  secret: your-jwt-secret-key-at-least-256-bits-long-change-in-production
#  expiration: 10000
  expiration: 604800000

server:
  port: 8085

ai-service:
  python-base-url: http://localhost:8000